name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Criterion
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: Snaipe
        repo: Criterion
        tag: v2.3.3
        file: criterion-v2.3.3-linux-x86_64.tar.bz2
    - name: Inflate Criterion
      run: tar xf criterion-v2.3.3-linux-x86_64.tar.bz2
    - name: Install Criterion
      run: sudo cp -R criterion-v2.3.3/* /usr/local
    - name: Update LDs
      run: sudo ldconfig
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
